### ISSUE TITLE
Potential Deserialization Issue (Long) & Operations List Fix

### ISSUE THREAD

**Issue by semse** [Revalto/ao-network#1]
Hi. First of all, thanks for creating this. I was able to successfully intercept packets and decode them with your solution.

There is 1 issue I found that I fixed. There is another one that I am not sure where it lies, but I suspect it's within deserialization.

First of all, the operations list needs to be fixed, as the codes are wrong. See following file for correct list: https://jsfiddle.net/tcLeqk8x/

However, I think there is an issue with deserialization. I looked at the parameters of some known packets. As an example: "HealthUpdate". I have annotated the known parameters. I suspect it's somewhere within the deserialization of the Long type. I don't know too much about working with buffers so it's hard for me to fix. 

{
  '0': 1048576,     //ObjectID --> Looks wrong. Should not be the same as '6'. It's (Int64Type / Long)
  '1': 67108864,  //Gametimestamp (I am pretty sure there is an issue here, because this does not change as time passes currently).      
  '2': -37,             //Damage Done, Health Received --> Looks Good
  '3': 1599          //New Health Value --> Looks good
  '4': 1,               //Effect Type     ---> Not sure if correct
  '5': 0,               //Effect Origin --> Not sure if correct
  '6': 1048576,  //ID of player causing damage. This should not be the same as parameter '0', so probably an issue here.
  '7': 65535,    //Spellytype
  '252': 6,
  type: 'HealthUpdate' // I added this property myself so I know which packet is which
}

**Comment by Revalto** [comment]
Thank you for the information and contribution to this repository. We will make a new list of packages in the near future.

I'll try to see what the problems might be. 

I apologize for such a long answer.
